version: "3.7"

services:
  app:
    build:
      args:
        uname: ${DOCKER_USERNAME}
        uid: ${DOCKER_USERID}
        gid: ${DOCKER_GROUPID}
      context: ./docker/php
      dockerfile: Dockerfile
    image: telegrambot
    container_name: telegrambot-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - telegrambot

  db:
    image: mysql:5.7
    container_name: telegrambot-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./storage/logs/sql/:/var/log/mysql/
      - ./docker/sql/cfg/:/etc/mysql/conf.d
    networks:
      -  telegrambot

  nginx:
    image: nginx:alpine
    container_name: telegrambot-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./storage/logs/nginx:/var/log/nginx/
      - ./:/var/www
      - ./docker/nginx/cfg/:/etc/nginx/conf.d/
    networks:
      - telegrambot

networks:
  telegrambot:
    driver: bridge
